{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2177af6-8944-4e2e-8eaa-8b369feb36bc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [23/May/2026 16:45:15] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [23/May/2026 16:45:28] \"GET /gratis-getraenk HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [23/May/2026 16:45:37] \"POST /gratis-getraenk HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [23/May/2026 16:45:47] \"GET /gratis-getraenk HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, request, render_template_string, redirect, url_for\n",
    "import sqlite3\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Veritabanını başlatan fonksiyon\n",
    "def init_db():\n",
    "    conn = sqlite3.connect('restoran.db')\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute('''\n",
    "        CREATE TABLE IF NOT EXISTS kunden (\n",
    "            email TEXT PRIMARY KEY,\n",
    "            newsletter_optin INTEGER\n",
    "        )\n",
    "    ''')\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "\n",
    "# Grepery Stüssihof Direkt Yorum Linki\n",
    "REVIEW_LINK = \"https://search.google.com/local/writereview?placeid=ChIJYUeEdL2hmkcRFa37o7FFCN0\"\n",
    "\n",
    "# 1. ANA SAYFA (QR KOD OKUTULUNCA AÇILACAK LİNK MENÜSÜ)\n",
    "HTML_LANDING = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"de\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "    <title>Willkommen bei Grepery</title>\n",
    "    <style>\n",
    "        body { \n",
    "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; \n",
    "            background-color: #fdfaf6; \n",
    "            margin: 0; \n",
    "            padding: 20px; \n",
    "            display: flex; \n",
    "            flex-direction: column; \n",
    "            align-items: center; \n",
    "        }\n",
    "        .logo-container { \n",
    "            text-align: center; \n",
    "            margin-bottom: 35px; \n",
    "            margin-top: 30px; \n",
    "        }\n",
    "        .logo-container h1 { \n",
    "            color: #800020; /* Bordo */\n",
    "            font-size: 36px; \n",
    "            margin: 0; \n",
    "            letter-spacing: 1px;\n",
    "        }\n",
    "        .logo-container p { \n",
    "            color: #777; \n",
    "            margin-top: 8px; \n",
    "            font-size: 16px;\n",
    "        }\n",
    "        .links-container { \n",
    "            width: 100%; \n",
    "            max-width: 380px; \n",
    "            display: flex; \n",
    "            flex-direction: column; \n",
    "            gap: 16px; \n",
    "        }\n",
    "        .link-btn { \n",
    "            display: flex; \n",
    "            align-items: center; \n",
    "            justify-content: center; \n",
    "            width: 100%; \n",
    "            padding: 16px; \n",
    "            background-color: white; \n",
    "            border: 2px solid #800020; /* Bordo */\n",
    "            border-radius: 14px; \n",
    "            color: #800020; /* Bordo */\n",
    "            font-size: 18px; \n",
    "            font-weight: bold; \n",
    "            text-decoration: none; \n",
    "            box-shadow: 0 4px 6px rgba(128, 0, 32, 0.08); \n",
    "            transition: all 0.3s ease; \n",
    "            box-sizing: border-box; \n",
    "        }\n",
    "        .link-btn:hover { \n",
    "            background-color: #800020; /* Bordo */\n",
    "            color: white; \n",
    "            transform: translateY(-3px); \n",
    "            box-shadow: 0 8px 15px rgba(128, 0, 32, 0.2); \n",
    "        }\n",
    "        .link-btn.highlight { \n",
    "            background-color: #800020; /* Bordo */\n",
    "            color: white; \n",
    "            border: none;\n",
    "            box-shadow: 0 6px 12px rgba(128, 0, 32, 0.3);\n",
    "        }\n",
    "        .link-btn.highlight:hover { \n",
    "            background-color: #5c0017; /* Koyu Bordo */\n",
    "            transform: translateY(-3px); \n",
    "            box-shadow: 0 10px 18px rgba(128, 0, 32, 0.4);\n",
    "        }\n",
    "        .emoji { \n",
    "            margin-right: 12px; \n",
    "            font-size: 24px; \n",
    "        }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "    <div class=\"logo-container\">\n",
    "        <h1>🥞 Grepery</h1>\n",
    "        <p>Schön, dass Sie da sind!</p>\n",
    "    </div>\n",
    "    \n",
    "    <div class=\"links-container\">\n",
    "        <!-- 1. Menu Linki -->\n",
    "        <a href=\"https://www.grepery.ch/menu\" class=\"link-btn\" target=\"_blank\">\n",
    "            <span class=\"emoji\">📖</span> Speisekarte\n",
    "        </a>\n",
    "        \n",
    "        <!-- 3. Hediye İçecek Linki (Dikkat çekici renk) -->\n",
    "        <a href=\"/gratis-getraenk\" class=\"link-btn highlight\">\n",
    "            <span class=\"emoji\">🍹</span> Gratis-Getränk sichern\n",
    "        </a>\n",
    "        \n",
    "        <!-- 2. Sosyal Medya Linki -->\n",
    "        <a href=\"https://www.instagram.com/grepery/\" class=\"link-btn\" target=\"_blank\">\n",
    "            <span class=\"emoji\">📸</span> Instagram\n",
    "        </a>\n",
    "        \n",
    "        <!-- 4. Website Linki -->\n",
    "        <a href=\"https://www.grepery.ch/\" class=\"link-btn\" target=\"_blank\">\n",
    "            <span class=\"emoji\">🌐</span> Webseite\n",
    "        </a>\n",
    "    </div>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# 2. ÜCRETSİZ İÇECEK FORMU (E-posta Alma Sayfası)\n",
    "HTML_GRATIS = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"de\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "    <title>Grepery - Gratis-Getränk</title>\n",
    "    <style>\n",
    "        body { \n",
    "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; \n",
    "            text-align: center; \n",
    "            margin-top: 30px; \n",
    "            background-color: #fdfaf6; \n",
    "        }\n",
    "        .back-link {\n",
    "            display: inline-block;\n",
    "            margin-bottom: 20px;\n",
    "            color: #777;\n",
    "            text-decoration: none;\n",
    "            font-size: 15px;\n",
    "            font-weight: bold;\n",
    "            transition: color 0.3s;\n",
    "        }\n",
    "        .back-link:hover { color: #800020; /* Bordo */ }\n",
    "        .container {\n",
    "            background-color: white;\n",
    "            padding: 30px;\n",
    "            border-radius: 15px;\n",
    "            box-shadow: 0 8px 20px rgba(0,0,0,0.06);\n",
    "            max-width: 400px;\n",
    "            margin: auto;\n",
    "            text-align: left;\n",
    "            position: relative;\n",
    "        }\n",
    "        h2 { \n",
    "            text-align: center; \n",
    "            color: #800020; /* Bordo */\n",
    "            margin-bottom: 20px;\n",
    "        }\n",
    "        input[type=\"email\"] { \n",
    "            padding: 14px; \n",
    "            margin: 15px 0; \n",
    "            font-size: 16px; \n",
    "            width: 100%;\n",
    "            border: 1px solid #e0e0e0;\n",
    "            border-radius: 10px;\n",
    "            box-sizing: border-box;\n",
    "            background-color: #fafafa;\n",
    "            transition: border 0.3s;\n",
    "        }\n",
    "        input[type=\"email\"]:focus {\n",
    "            outline: none;\n",
    "            border-color: #800020; /* Bordo */\n",
    "            background-color: #fff;\n",
    "        }\n",
    "        .checkbox-container {\n",
    "            font-size: 14px;\n",
    "            margin-bottom: 25px;\n",
    "            color: #555;\n",
    "            display: flex;\n",
    "            align-items: flex-start;\n",
    "            line-height: 1.5;\n",
    "            background-color: #fafafa;\n",
    "            padding: 12px;\n",
    "            border-radius: 8px;\n",
    "            border: 1px solid #eee;\n",
    "        }\n",
    "        .checkbox-container input {\n",
    "            margin-top: 4px;\n",
    "            margin-right: 12px;\n",
    "            transform: scale(1.2);\n",
    "        }\n",
    "        button { \n",
    "            padding: 15px 20px; \n",
    "            font-size: 16px; \n",
    "            border: none; \n",
    "            border-radius: 10px; \n",
    "            cursor: pointer;\n",
    "            width: 100%;\n",
    "            transition: 0.3s;\n",
    "        }\n",
    "        .btn-submit { \n",
    "            background-color: #800020; /* Bordo */\n",
    "            color: white; \n",
    "            font-weight: bold;\n",
    "            box-shadow: 0 4px 10px rgba(128, 0, 32, 0.2);\n",
    "        }\n",
    "        .btn-submit:hover { \n",
    "            background-color: #5c0017; /* Koyu Bordo */\n",
    "            transform: translateY(-2px);\n",
    "        }\n",
    "        .btn-google { \n",
    "            background-color: #4285F4; \n",
    "            color: white; \n",
    "            font-weight: bold; \n",
    "            margin-top: 15px;\n",
    "            box-shadow: 0 4px 10px rgba(66, 133, 244, 0.2);\n",
    "        }\n",
    "        .btn-google:hover { \n",
    "            background-color: #3367d6; \n",
    "            transform: translateY(-2px);\n",
    "        }\n",
    "        .error { \n",
    "            color: #e74c3c; \n",
    "            font-weight: bold; \n",
    "            text-align: center; \n",
    "            font-size: 15px; \n",
    "            background-color: #fdf2f0;\n",
    "            padding: 10px;\n",
    "            border-radius: 8px;\n",
    "        }\n",
    "        .success-text { \n",
    "            color: #800020; /* Bordo */\n",
    "            font-size: 24px; \n",
    "            font-weight: bold; \n",
    "            text-align: center; \n",
    "            margin-bottom: 10px;\n",
    "        }\n",
    "        .friendly-box { \n",
    "            background-color: #f8eef0; /* Açık Bordo/Pembe Arka Plan */\n",
    "            color: #5c0017; /* Koyu Bordo Metin */\n",
    "            font-size: 15px; \n",
    "            text-align: center; \n",
    "            padding: 20px; \n",
    "            border-radius: 12px; \n",
    "            margin-bottom: 20px;\n",
    "            line-height: 1.6;\n",
    "            border: 1px dashed #800020; /* Bordo Kesik Çizgi */\n",
    "        }\n",
    "        .footer-text { \n",
    "            font-size: 12px; \n",
    "            color: #aaa; \n",
    "            margin-top: 20px; \n",
    "            text-align: center;\n",
    "        }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "    <a href=\"/\" class=\"back-link\">⬅️ Zurück zum Menü</a>\n",
    "    \n",
    "    <div class=\"container\">\n",
    "        <h2>🍹 Dein Gratis-Getränk</h2>\n",
    "        \n",
    "        {% if mesaj %}\n",
    "            <p class=\"error\">{{ mesaj }}</p>\n",
    "        {% endif %}\n",
    "        \n",
    "        {% if basarili %}\n",
    "            <p class=\"success-text\">Herzlichen Dank! ❤️</p>\n",
    "            \n",
    "            <div class=\"friendly-box\">\n",
    "                <b>Fast geschafft! 🎉</b><br><br>\n",
    "                Klicken Sie auf den Button unten, um uns zu bewerten. Zeigen Sie danach einfach den Bewertungsbildschirm unserem Team, und schon bringen wir Ihnen Ihr Erfrischungsgetränk! 🥂\n",
    "            </div>\n",
    "            \n",
    "            <a href=\"{{ review_link }}\" target=\"_blank\" style=\"text-decoration: none;\">\n",
    "                <button class=\"btn-google\">⭐ Auf Google bewerten</button>\n",
    "            </a>\n",
    "        {% else %}\n",
    "            <p style=\"text-align: center; color: #555; margin-bottom: 20px;\">Geben Sie Ihre E-Mail-Adresse ein, um Ihr Gratis-Getränk zu erhalten:</p>\n",
    "            <form method=\"POST\" action=\"/gratis-getraenk\">\n",
    "                <input type=\"email\" name=\"email\" placeholder=\"beispiel@email.com\" required>\n",
    "                \n",
    "                <label class=\"checkbox-container\">\n",
    "                    <input type=\"checkbox\" name=\"newsletter\" value=\"1\">\n",
    "                    Ich möchte über leckere Neuigkeiten und Events von Grepery informiert werden. 🥞\n",
    "                </label>\n",
    "                \n",
    "                <button class=\"btn-submit\" type=\"submit\">Weiter ➔</button>\n",
    "            </form>\n",
    "            <p class=\"footer-text\">* Jede E-Mail-Adresse kann nur einmal teilnehmen.</p>\n",
    "        {% endif %}\n",
    "    </div>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# Route 1: QR Kod okutulunca açılan ana menü\n",
    "@app.route(\"/\", methods=[\"GET\"])\n",
    "def ana_sayfa():\n",
    "    return render_template_string(HTML_LANDING)\n",
    "\n",
    "# Route 2: Bedava İçecek / E-posta Alma sayfası\n",
    "@app.route(\"/gratis-getraenk\", methods=[\"GET\", \"POST\"])\n",
    "def gratis_getraenk():\n",
    "    if request.method == \"POST\":\n",
    "        email = request.form.get(\"email\")\n",
    "        newsletter_optin = 1 if request.form.get(\"newsletter\") else 0\n",
    "        \n",
    "        conn = sqlite3.connect('restoran.db')\n",
    "        cursor = conn.cursor()\n",
    "        \n",
    "        # E-posta adresinin daha önce kullanılıp kullanılmadığını kontrol et\n",
    "        cursor.execute(\"SELECT * FROM kunden WHERE email = ?\", (email,))\n",
    "        kayit = cursor.fetchone()\n",
    "        \n",
    "        if kayit:\n",
    "            conn.close()\n",
    "            # E-posta bulunduysa hata mesajı göster\n",
    "            return render_template_string(HTML_GRATIS, mesaj=\"Sie haben mit dieser E-Mail-Adresse bereits ein Getränk erhalten. 😊\", basarili=False)\n",
    "        else:\n",
    "            # E-posta bulunamadıysa kaydet ve başarılı sayfasını göster (Sadece 1 kez hakkı oluyor)\n",
    "            cursor.execute(\"INSERT INTO kunden (email, newsletter_optin) VALUES (?, ?)\", (email, newsletter_optin))\n",
    "            conn.commit()\n",
    "            conn.close()\n",
    "            \n",
    "            return render_template_string(HTML_GRATIS, basarili=True, review_link=REVIEW_LINK)\n",
    "            \n",
    "    # GET isteği gelirse boş formu göster\n",
    "    return render_template_string(HTML_GRATIS, basarili=False)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    init_db()\n",
    "    app.run(port=5000, debug=True, use_reloader=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
